### ISSUE TITLE
CoC RFC

### ISSUE THREAD

**Issue by danielpclark** [rubyforgood/loudoun_codes#129]
I see CoC 1.3.0 has been approved.  If I may add I really like the direction Matz went with the CoC discussion in choosing the PostrgreSQL CoC ([The Ruby Community Conduct Guideline](https://www.ruby-lang.org/en/conduct/)) which has one important statement this CoC doesn't include:

> When interpreting the words and actions of others, participants should always assume good intentions.

The current CoC here doesn't reflect “assuming the best” or give any statement as to trying to make amends.  This CoC strictly focuses on negative aspects and enforcement.  So whereas I'm okay with the policy itself — I don't feel it properly reflects a positive ideology for keeping the peace.

**Comment by bokmann** [comment]
As an organizer of several conferences and some involved in diversity efforts at several places I've worked, I've been in a zillion code of conduct conversations.  Whilte Coralines code of conduct isn't perfect, the one Matz chose is a disaster.  It's too aspirational, and says nothing about enforcement of how to report issues.  

As outlined by Ashe Dryden here: https://www.ashedryden.com/blog/codes-of-conduct-101-faq

a code of conduct needs to include:
 - statement of unacceptable behavior
 - how the policy will be enforced
 - how and whom to make an incident report to
 - training and reference materials for organizers, staff, and volunteers on how to respond to incident reports

I really don't want to open this can of worms on this project.  Other open source projects I maintain use the same code of conduct and have for years.
